services:
  tradebot:
    image: ghcr.io/rohithbv/tradebot:${GIT_COMMIT_HASH:-latest}
    ports:
      - ":8080"
    environment:
      - TRADEBOT_DB_PATH=/data/tradebot.db
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - tradebot-data:/data
    restart: unless-stopped
    deploy:
      update_config:
        order: start-first

volumes:
  tradebot-data:
